pv_systems:
  - name: PV_Mitte
    panel_angle_deg: 30
    efficiency: 0.18
    location:
      lat: 52.52
      lon: 13.405
    date: 2025-05-01

wind_systems:
  - name: Wind_Nord
    rated_power: 3000
    cut_in: 3
    cut_out: 25
    rated_speed: 12
    location:
      lat: 53.5511
      lon: 9.9937
    date: 2025-05-01