pv_systems:
- D_soil: 0.1
  age: 3
  albedo: 0.1
  azimut: 130
  date: '2025-05-14'
  location:
    lat: 52.0
    lon: 12.0
  name: Dresden_1
  rated_power: 10.0
  shading: 0.1
  size: 1000.0
  tilt: 20
wind_systems: []
