pv_systems: []
wind_systems:
- alpha: 0.0
  cut_in: 3.0
  cut_out: 25.0
  date: '2025-05-23'
  hub_height: 40.0
  location:
    lat: 52.0
    lon: 14.0
  name: Dresen Wind
  rated_power: 180.0
  rated_speed: 12.0
  rotor_radius: 50.0
  turbines: 60
  wake_loss: 0.0
